In [1]:
import numpy as np
import pandas as pd

#matplotlib and seaborn as used for data visualization
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
from urllib.request import urlopen
from bs4 import BeautifulSoup

In [92]:
tw = pd.read_csv('Twitter.csv',header=None,names=['text','Sentiment'])
tw.head()

text  Sentiment
0  when modi promised “minimum government maximum...       -1.0
1  talk all the nonsense and continue all the dra...        0.0
2  what did just say vote for modi  welcome bjp t...        1.0
3  asking his supporters prefix chowkidar their n...        1.0
4  answer who among these the most powerful world...        1.0

In [93]:
tw['Sentiment'].value_counts()

 1.0    72250
 0.0    55213
-1.0    35510
Name: Sentiment, dtype: int64

In [94]:
tw = tw.iloc[:20000]

In [95]:
tw['Sentiment'].value_counts()

 1.0    8374
 0.0    6807
-1.0    4819
Name: Sentiment, dtype: int64

In [38]:
pip install wordcloud

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\Cyanb\anaconda3\python.exe -m pip install --upgrade pip' command.


In [39]:
import string
import nltk
import re
from nltk.corpus import stopwords
from nltk.tokenize import RegexpTokenizer
from wordcloud import STOPWORDS
from sklearn.feature_extraction.text import CountVectorizer

In [96]:
tw['Sentiment'].isnull().values.any()

False

In [97]:
tw['text'].isnull().values.any()

True

In [98]:
tw = tw[tw['text'].notna()]

In [99]:
tw['text'].isnull().values.any()

False

In [100]:
def Text_clean(text):
    text=re.sub(r' \n|\n', ' ', text)
    text = re.sub(r'http\S+', '', text, flags=re.MULTILINE)
    text = re.sub(r'@\S+', '', text, flags=re.MULTILINE)
    text = re.sub(r'#', '', text, flags=re.MULTILINE)
    text = re.sub(r'，', '', text, flags=re.MULTILINE)
    text = re.sub(r'！', '', text, flags=re.MULTILINE)
    text = re.sub(r'？', '', text, flags=re.MULTILINE)
    text = re.sub(r'。', '', text, flags=re.MULTILINE)
    text = re.sub(r'“', '', text, flags=re.MULTILINE)
    text = re.sub(r'”', '', text, flags=re.MULTILINE)
    text = re.sub(r'、', '', text, flags=re.MULTILINE)
    text=re.sub('[%s]' % re.escape(string.punctuation), ' ',text)
    text = re.sub('\w*\d\w*', '', text)
    return text

round=lambda x:Text_clean(x)

In [101]:
tw['text']=pd.DataFrame(tw['text'].apply(round))

In [102]:
corpus=[]
for index, r in tw.iterrows():
        text=r['text']
        corpus.append(text)
corpus[:5]

['when modi promised minimum government maximum governance expected him begin the difficult job reforming the state why does take years get justice state should and not business and should exit psus and temples',
 'talk all the nonsense and continue all the drama will vote for modi ',
 'what did just say vote for modi  welcome bjp told you rahul the main campaigner for modi think modi should just relax',
 'asking his supporters prefix chowkidar their names modi did great service now there confusion what read what not now crustal clear what will crass filthy nonsensical see how most abuses are coming from chowkidars',
 'answer who among these the most powerful world leader today trump putin modi may ']

In [103]:
len(corpus)

19999

In [104]:
attitudes=[]
for index, r in tw.iterrows():
        text=r['Sentiment']
        attitudes.append(text)
attitudes[:20]

[-1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 1.0,
 -1.0]

In [105]:
cv = CountVectorizer()
X=cv.fit_transform(corpus)
print (cv.get_feature_names())
print(X.toarray())

['aaa', 'aache', 'aacstra', 'aadani', 'aadar', 'aadarsh', 'aadat', 'aadesh', 'aadhaar', 'aadhaarenabled', 'aadhaarshare', 'aadhar', 'aadivasis', 'aadmi', 'aaega', 'aaenge', 'aagar', 'aagaye', 'aage', 'aagr', 'aagya', 'aah', 'aai', 'aaiyaar', 'aaiye', 'aaj', 'aajtak', 'aak', 'aaka', 'aakash', 'aake', 'aakhir', 'aakhri', 'aakhya', 'aal', 'aalosoda', 'aalu', 'aam', 'aambani', 'aamin', 'aamir', 'aane', 'aankh', 'aankhein', 'aankhon', 'aanshu', 'aao', 'aap', 'aapa', 'aapas', 'aapcong', 'aapevadu', 'aapies', 'aapjds', 'aapka', 'aapke', 'aapki', 'aapko', 'aapna', 'aapnechamche', 'aaps', 'aaptard', 'aaptardmind', 'aaram', 'aarop', 'aaropo', 'aarti', 'aaryan', 'aashish', 'aasteen', 'aata', 'aatankwaad', 'aatankwadi', 'aate', 'aati', 'aaukant', 'aawe', 'aay', 'aaya', 'aaye', 'aayega', 'aayege', 'aayenge', 'aayi', 'aayog', 'aayushman', 'abandon', 'abandoned', 'abandoning', 'abb', 'abba', 'abbe', 'abberrant', 'abbreviation', 'abbreviations', 'abcd', 'abd', 'abdicating', 'abdication', 'abducted', '

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [106]:
bow=pd.DataFrame(X.toarray())
bow.columns=cv.get_feature_names()
bow.head()

aaa  aache  aacstra  aadani  aadar  aadarsh  aadat  aadesh  aadhaar  \
0    0      0        0       0      0        0      0       0        0   
1    0      0        0       0      0        0      0       0        0   
2    0      0        0       0      0        0      0       0        0   
3    0      0        0       0      0        0      0       0        0   
4    0      0        0       0      0        0      0       0        0   

   aadhaarenabled  ...  हनद  চৰক  ஜகஆட  ಉಪಯ  ತಮಭ  ನನಗ  ಮನದ  ರತಕ  ರದಲ  ളവർക  
0               0  ...    0    0     0    0    0    0    0    0    0     0  
1               0  ...    0    0     0    0    0    0    0    0    0     0  
2               0  ...    0    0     0    0    0    0    0    0    0     0  
3               0  ...    0    0     0    0    0    0    0    0    0     0  
4               0  ...    0    0     0    0    0    0    0    0    0     0  

[5 rows x 28249 columns]

In [108]:
bow.shape

(19999, 28249)

In [109]:
cv = CountVectorizer(stop_words='english')
S=cv.fit_transform(corpus)

bow_S=pd.DataFrame(S.toarray())
bow_S.columns=cv.get_feature_names()
bow_S.head()

aaa  aache  aacstra  aadani  aadar  aadarsh  aadat  aadesh  aadhaar  \
0    0      0        0       0      0        0      0       0        0   
1    0      0        0       0      0        0      0       0        0   
2    0      0        0       0      0        0      0       0        0   
3    0      0        0       0      0        0      0       0        0   
4    0      0        0       0      0        0      0       0        0   

   aadhaarenabled  ...  हनद  চৰক  ஜகஆட  ಉಪಯ  ತಮಭ  ನನಗ  ಮನದ  ರತಕ  ರದಲ  ളവർക  
0               0  ...    0    0     0    0    0    0    0    0    0     0  
1               0  ...    0    0     0    0    0    0    0    0    0     0  
2               0  ...    0    0     0    0    0    0    0    0    0     0  
3               0  ...    0    0     0    0    0    0    0    0    0     0  
4               0  ...    0    0     0    0    0    0    0    0    0     0  

[5 rows x 27980 columns]

In [110]:
bow_S.shape

(19999, 27980)

In [111]:
tw_token=tw.copy()

In [112]:
tokenizer=RegexpTokenizer(r'\w+')
tw_token['text']=tw_token['text'].apply(lambda x: tokenizer.tokenize(x.lower())) #Also converts all upper cases to lower cases
tw_token.head(20)

text  Sentiment
0   [when, modi, promised, minimum, government, ma...       -1.0
1   [talk, all, the, nonsense, and, continue, all,...        0.0
2   [what, did, just, say, vote, for, modi, welcom...        1.0
3   [asking, his, supporters, prefix, chowkidar, t...        1.0
4   [answer, who, among, these, the, most, powerfu...        1.0
5      [kiya, tho, refresh, maarkefir, comment, karo]        0.0
6   [surat, women, perform, yagna, seeks, divine, ...        0.0
7   [this, comes, from, cabinet, which, has, schol...        0.0
8   [with, upcoming, election, india, saga, going,...        1.0
9                      [gandhi, was, gay, does, modi]        1.0
10  [things, like, demonetisation, gst, goods, and...        1.0
11  [hope, tuthukudi, people, would, prefer, hones...        1.0
12            [calm, waters, wheres, the, modi, wave]        1.0
13  [one, vote, can, make, all, the, difference, a...        0.0
14  [one, vote, can, make, all, the, difference, a...        0.0
15  [vote, such, party, and, leadershipwho, can, t...       -1.0
16         [vote, modi, who, has, not, created, jobs]        0.0
17  [through, our, vote, ensure, govt, need, and, ...        0.0
18  [dont, play, with, the, words, was, talking, a...        1.0
19  [didn, write, chowkidar, does, mean, anti, mod...       -1.0

In [113]:
tw.head()

text  Sentiment
0  when modi promised minimum government maximum ...       -1.0
1  talk all the nonsense and continue all the dra...        0.0
2  what did just say vote for modi  welcome bjp t...        1.0
3  asking his supporters prefix chowkidar their n...        1.0
4  answer who among these the most powerful world...        1.0

In [114]:
tw_token.head()

text  Sentiment
0  [when, modi, promised, minimum, government, ma...       -1.0
1  [talk, all, the, nonsense, and, continue, all,...        0.0
2  [what, did, just, say, vote, for, modi, welcom...        1.0
3  [asking, his, supporters, prefix, chowkidar, t...        1.0
4  [answer, who, among, these, the, most, powerfu...        1.0

In [119]:
import nltk
nltk.download('stopwords')
def Remove_StopW(text):
    words=[w for w in text if w not in stopwords.words('english')]
    return words

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Cyanb\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


In [120]:
tw_token['text']=tw_token['text'].apply(lambda x:Remove_StopW(x))
tw_token['text'].head()

0    [modi, promised, minimum, government, maximum,...
1        [talk, nonsense, continue, drama, vote, modi]
2    [say, vote, modi, welcome, bjp, told, rahul, m...
3    [asking, supporters, prefix, chowkidar, names,...
4    [answer, among, powerful, world, leader, today...
Name: text, dtype: object

In [121]:
from nltk.stem import WordNetLemmatizer 

In [125]:
nltk.download('wordnet')
lemmatizer = WordNetLemmatizer ()
def lem(text):
    lemmed=[lemmatizer.lemmatize(i) for i in text]
    return lemmed

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Cyanb\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\wordnet.zip.


In [126]:
tw_token['text'].apply(lambda x:lem(x))

0        [modi, promised, minimum, government, maximum,...
1            [talk, nonsense, continue, drama, vote, modi]
2        [say, vote, modi, welcome, bjp, told, rahul, m...
3        [asking, supporter, prefix, chowkidar, name, m...
4        [answer, among, powerful, world, leader, today...
                               ...                        
19995                [sushil, modi, destroyer, bihar, bjp]
19996    [new, post, west, bengal, modi, bjp, collision...
19997    [yes, everyone, fool, everyone, cant, fooled, ...
19998    [eastern, indian, state, west, bengal, prime, ...
19999    [mentioned, kashmiri, muslim, suffering, pulwa...
Name: text, Length: 19999, dtype: object

In [127]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.model_selection import train_test_split

In [128]:
tw_copy=tw.copy()

In [129]:
train,test = train_test_split(tw_copy,test_size=0.2,random_state=42)

In [130]:
tw_train=[]
for i in train['text']:
    tw_train.append(i)
tw_test=[]
for i in test['text']:
    tw_test.append(i)

In [245]:
from sklearn.feature_extraction.text import CountVectorizer
cv_class = CountVectorizer()
train_features= cv_class.fit_transform(tw_train)
test_features=cv_class.transform(tw_test)

In [132]:
Classifiers = [
    LogisticRegression(),
    GaussianNB(),
    DecisionTreeClassifier(max_depth=1),
    RandomForestClassifier(n_estimators=200)]

In [246]:
Classifiers = [
    LogisticRegression(),
    GaussianNB(),
    DecisionTreeClassifier(max_depth=1),
    RandomForestClassifier(n_estimators=200)]

In [247]:
dense_features=train_features.toarray()
dense_test= test_features.toarray()
Accuracy=[]
Model=[]
for classifier in Classifiers:
    try:
        fit = classifier.fit(train_features,train['Sentiment'])
        pred = fit.predict(test_features)
    except Exception:
        fit = classifier.fit(dense_features,train['Sentiment'])
        pred = fit.predict(dense_test)
    accuracy = accuracy_score(pred,test['Sentiment'])
    Accuracy.append(accuracy)
    Model.append(classifier.__class__.__name__)

for i in range(len(Accuracy)):
    print (Model[i],": ",Accuracy[i])

C:\Users\Cyanb\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression :  0.87575
GaussianNB :  0.544
DecisionTreeClassifier :  0.41825
RandomForestClassifier :  0.789


In [150]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

In [243]:
logreg = LogisticRegression(solver='liblinear')
logreg.fit(train_features, train['Sentiment'])
pred = logreg.predict(test_features)
print('The Micro Precision score is',precision_score(test['Sentiment'], pred, average='micro'),'\n')
#print(confusion_matrix(test['Sentiment'],pred))
print(classification_report(test['Sentiment'],pred))

The Micro Precision score is 0.87475 

              precision    recall  f1-score   support

        -1.0       0.87      0.75      0.81       974
         0.0       0.85      0.96      0.90      1353
         1.0       0.90      0.88      0.89      1673

    accuracy                           0.87      4000
   macro avg       0.87      0.86      0.87      4000
weighted avg       0.88      0.87      0.87      4000



In [214]:
from scipy.sparse import csr_matrix

In [262]:
words=input()
def Text_clean(text):
    text=re.sub(r' \n|\n', ' ', text)
    text = re.sub(r'http\S+', '', text, flags=re.MULTILINE)
    text = re.sub(r'@\S+', '', text, flags=re.MULTILINE)
    text = re.sub(r'#', '', text, flags=re.MULTILINE)
    text = re.sub(r'，', '', text, flags=re.MULTILINE)
    text = re.sub(r'！', '', text, flags=re.MULTILINE)
    text = re.sub(r'？', '', text, flags=re.MULTILINE)
    text = re.sub(r'。', '', text, flags=re.MULTILINE)
    text = re.sub(r'“', '', text, flags=re.MULTILINE)
    text = re.sub(r'”', '', text, flags=re.MULTILINE)
    text = re.sub(r'、', '', text, flags=re.MULTILINE)
    text=re.sub('[%s]' % re.escape(string.punctuation), ' ',text)
    text = re.sub('\w*\d\w*', '', text)
    return text

round=lambda x:Text_clean(x)
words=Text_clean(words)
#corpus
corpus=[]
corpus.append(words)
#Vecoterization
#cv_class = CountVectorizer()
test_sentence=cv_class.transform(corpus)
#test_sentence = csr_matrix((test_sentence),shape=(1600,16000))
#predict
#logreg.fit(test_sentence.shape[0],test_sentence.shape[1])
predict = logreg.predict(test_sentence)


print(predict)

Im so sad
[-1.]


In [252]:
cv_class.vocabulary_

{'now': 15661,
 'remember': 18750,
 'modi': 14488,
 'used': 23558,
 'say': 19799,
 'that': 22329,
 'want': 24092,
 'give': 9016,
 'computer': 4576,
 'education': 6953,
 'employment': 7140,
 'end': 7176,
 'the': 22354,
 'poverty': 17341,
 'any': 1131,
 'person': 16759,
 'will': 24411,
 'deliver': 5767,
 'less': 12940,
 'than': 22310,
 'what': 24291,
 'thinks': 22457,
 'tax': 22093,
 'payer': 16561,
 'paisa': 16237,
 'aise': 647,
 'free': 8495,
 'baatne': 1744,
 'liye': 13132,
 'hai': 9545,
 'kya': 12585,
 'stop': 21378,
 'ayushman': 1709,
 'bharat': 2455,
 'scheme': 19865,
 'then': 22389,
 'see': 20004,
 'hopeful': 10225,
 'tive': 22658,
 'namo': 15128,
 'comes': 4426,
 'again': 507,
 'scamgress': 19824,
 'sorry': 20983,
 'congress': 4691,
 'shit': 20374,
 'can': 3385,
 'bet': 2345,
 'life': 13021,
 'this': 22466,
 'know': 12456,
 'come': 4417,
 'back': 1772,
 'uss': 23579,
 'chutiya': 4128,
 'pappu': 16341,
 'ghnata': 8959,
 'vote': 23979,
 'dengy': 5853,
 'log': 13176,
 'she': 20316,


In [263]:
import pickle

with open('classifier', 'wb') as fout:
    pickle.dump((cv_class, logreg), fout)

In [ ]:
import pickle

with open('classifier.pkl', 'rb') as f:
    cv_class, logreg = pickle.load(f)